CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20260926045945_InitialCreate') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20260926045945_InitialCreate') THEN
    INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260926045945_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'zonamatch') THEN
            CREATE SCHEMA zonamatch;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'zonamatch') THEN
            CREATE SCHEMA zonamatch;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE EXTENSION IF NOT EXISTS hstore;
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'zonamatch') THEN
            CREATE SCHEMA zonamatch;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.data_sources (
        id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
        code character varying(64) NOT NULL,
        name character varying(200) NOT NULL,
        kind smallint NOT NULL,
        publisher character varying(200),
        url character varying(500),
        license character varying(100),
        CONSTRAINT pk_data_sources PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.poi_categories (
        id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
        code character varying(64) NOT NULL,
        name character varying(120) NOT NULL,
        parent_id smallint,
        sort_order smallint NOT NULL,
        CONSTRAINT pk_poi_categories PRIMARY KEY (id),
        CONSTRAINT fk_poi_categories_poi_categories_parent_id FOREIGN KEY (parent_id) REFERENCES zonamatch.poi_categories (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.territorial_units (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        type smallint NOT NULL,
        code character varying(32),
        name character varying(200) NOT NULL,
        normalized_name character varying(200) NOT NULL,
        parent_id bigint,
        geometry geometry(MultiPolygon,4326) NOT NULL,
        area_m2 double precision NOT NULL,
        data_source_id smallint NOT NULL,
        external_id character varying(128) NOT NULL,
        source_date date,
        imported_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_territorial_units PRIMARY KEY (id),
        CONSTRAINT fk_territorial_units_data_sources_data_source_id FOREIGN KEY (data_source_id) REFERENCES zonamatch.data_sources (id) ON DELETE RESTRICT,
        CONSTRAINT fk_territorial_units_territorial_units_parent_id FOREIGN KEY (parent_id) REFERENCES zonamatch.territorial_units (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.poi_mapping_rules (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
        data_source_id smallint NOT NULL,
        attribute character varying(64) NOT NULL,
        value character varying(128) NOT NULL,
        category_id smallint NOT NULL,
        priority integer NOT NULL,
        CONSTRAINT pk_poi_mapping_rules PRIMARY KEY (id),
        CONSTRAINT fk_poi_mapping_rules_data_sources_data_source_id FOREIGN KEY (data_source_id) REFERENCES zonamatch.data_sources (id) ON DELETE CASCADE,
        CONSTRAINT fk_poi_mapping_rules_poi_categories_category_id FOREIGN KEY (category_id) REFERENCES zonamatch.poi_categories (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.points_of_interest (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        category_id smallint NOT NULL,
        name character varying(300) NOT NULL,
        normalized_name character varying(300) NOT NULL,
        address character varying(300),
        location geometry(Point,4326) NOT NULL,
        footprint geometry(Geometry,4326),
        ownership smallint NOT NULL,
        attributes jsonb NOT NULL,
        data_source_id smallint NOT NULL,
        external_id character varying(128) NOT NULL,
        source_date date,
        imported_at timestamp with time zone NOT NULL,
        canonical_poi_id bigint,
        CONSTRAINT pk_points_of_interest PRIMARY KEY (id),
        CONSTRAINT fk_points_of_interest_data_sources_data_source_id FOREIGN KEY (data_source_id) REFERENCES zonamatch.data_sources (id) ON DELETE RESTRICT,
        CONSTRAINT fk_points_of_interest_poi_categories_category_id FOREIGN KEY (category_id) REFERENCES zonamatch.poi_categories (id) ON DELETE RESTRICT,
        CONSTRAINT fk_points_of_interest_points_of_interest_canonical_poi_id FOREIGN KEY (canonical_poi_id) REFERENCES zonamatch.points_of_interest (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.territorial_indicators (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        territorial_unit_id bigint NOT NULL,
        indicator_code character varying(64) NOT NULL,
        value numeric(18,4) NOT NULL,
        unit character varying(32) NOT NULL,
        data_source_id smallint NOT NULL,
        reference_date date NOT NULL,
        CONSTRAINT pk_territorial_indicators PRIMARY KEY (id),
        CONSTRAINT fk_territorial_indicators_data_sources_data_source_id FOREIGN KEY (data_source_id) REFERENCES zonamatch.data_sources (id) ON DELETE RESTRICT,
        CONSTRAINT fk_territorial_indicators_territorial_units_territorial_unit_id FOREIGN KEY (territorial_unit_id) REFERENCES zonamatch.territorial_units (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.zones (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        territorial_unit_id bigint NOT NULL,
        slug character varying(160) NOT NULL,
        name character varying(200) NOT NULL,
        parent_name character varying(200) NOT NULL,
        CONSTRAINT pk_zones PRIMARY KEY (id),
        CONSTRAINT fk_zones_territorial_units_territorial_unit_id FOREIGN KEY (territorial_unit_id) REFERENCES zonamatch.territorial_units (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE TABLE zonamatch.zone_adjacencies (
        zone_id integer NOT NULL,
        neighbor_zone_id integer NOT NULL,
        CONSTRAINT pk_zone_adjacencies PRIMARY KEY (zone_id, neighbor_zone_id),
        CONSTRAINT fk_zone_adjacencies_zones_neighbor_zone_id FOREIGN KEY (neighbor_zone_id) REFERENCES zonamatch.zones (id) ON DELETE CASCADE,
        CONSTRAINT fk_zone_adjacencies_zones_zone_id FOREIGN KEY (zone_id) REFERENCES zonamatch.zones (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (1, 'zm-comunas', 1, 'CC BY 2.5 AR', 'Comunas de CABA', 'GCBA · Buenos Aires Data', 'https://data.buenosaires.gob.ar/dataset/comunas');
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (2, 'zm-partidos', 1, 'CC BY 4.0', 'Partidos de la Provincia de Buenos Aires', 'Datos Abiertos PBA', 'https://catalogo.datos.gba.gob.ar/');
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (3, 'zm-radios', 1, 'CC BY 4.0', 'Radios censales 2022', 'INDEC', 'https://www.indec.gob.ar/indec/web/Institucional-Indec-Codgeo');
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (4, 'zm-escuelas', 1, 'CC BY 4.0', 'Padrón de establecimientos educativos', 'DGCyE PBA', 'https://abc.gob.ar/');
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (5, 'osm', 2, 'ODbL 1.0', 'OpenStreetMap', 'OpenStreetMap contributors', 'https://www.openstreetmap.org/copyright');
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (6, 'ba-barrios', 1, 'CC BY 2.5 AR', 'Barrios de CABA', 'GCBA · Buenos Aires Data', 'https://data.buenosaires.gob.ar/dataset/barrios');
    INSERT INTO zonamatch.data_sources (id, code, kind, license, name, publisher, url)
    VALUES (7, 'community', 2, NULL, 'Aportes de vecinos', 'Comunidad ZonaMatch', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (1, 'transporte', 'Transporte', NULL, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (2, 'educacion', 'Educación', NULL, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (3, 'salud', 'Salud', NULL, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (4, 'comercios_servicios', 'Comercios y servicios', NULL, 4);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (5, 'deporte', 'Deporte', NULL, 5);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (6, 'espacios_verdes', 'Espacios verdes', NULL, 6);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (7, 'cultura_gastronomia', 'Cultura y gastronomía', NULL, 7);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (101, 'transporte.estacion_tren', 'Estación de tren', 1, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (102, 'transporte.subte', 'Estación de subte', 1, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (103, 'transporte.parada_colectivo', 'Parada de colectivo', 1, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (104, 'transporte.premetro', 'Parada de premetro', 1, 4);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (201, 'educacion.jardin', 'Jardín', 2, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (202, 'educacion.primaria', 'Escuela primaria', 2, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (203, 'educacion.secundaria', 'Escuela secundaria', 2, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (204, 'educacion.escuela', 'Escuela (nivel sin informar)', 2, 4);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (205, 'educacion.superior', 'Universidad o instituto superior', 2, 5);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (301, 'salud.hospital', 'Hospital', 3, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (302, 'salud.clinica', 'Clínica o consultorio', 3, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (303, 'salud.centro_salud', 'Centro de salud (CESAC / CAPS)', 3, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (401, 'comercios_servicios.supermercado', 'Supermercado', 4, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (402, 'comercios_servicios.farmacia', 'Farmacia', 4, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (403, 'comercios_servicios.banco', 'Banco', 4, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (501, 'deporte.gimnasio', 'Gimnasio', 5, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (502, 'deporte.club', 'Club o polideportivo', 5, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (503, 'deporte.natatorio', 'Natatorio', 5, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (504, 'deporte.cancha', 'Cancha', 5, 4);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (601, 'espacios_verdes.plaza_parque', 'Plaza o parque', 6, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (602, 'espacios_verdes.reserva', 'Reserva natural', 6, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (701, 'cultura_gastronomia.teatro', 'Teatro', 7, 1);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (702, 'cultura_gastronomia.museo', 'Museo', 7, 2);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (703, 'cultura_gastronomia.cine', 'Cine', 7, 3);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (704, 'cultura_gastronomia.restaurante', 'Restaurante', 7, 4);
    INSERT INTO zonamatch.poi_categories (id, code, name, parent_id, sort_order)
    VALUES (705, 'cultura_gastronomia.cafe_bar', 'Café o bar', 7, 5);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (1, 'station', 102, 5, 5, 'subway');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (2, 'railway', 102, 5, 10, 'subway_entrance');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (3, 'railway', 101, 5, 10, 'station');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (4, 'railway', 101, 5, 10, 'halt');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (5, 'highway', 103, 5, 10, 'bus_stop');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (6, 'railway', 104, 5, 10, 'tram_stop');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (10, 'amenity', 201, 5, 10, 'kindergarten');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (11, 'amenity', 204, 5, 10, 'school');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (12, 'amenity', 205, 5, 10, 'college');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (13, 'amenity', 205, 5, 10, 'university');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (20, 'healthcare', 303, 5, 5, 'centre');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (21, 'amenity', 301, 5, 10, 'hospital');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (22, 'amenity', 302, 5, 10, 'clinic');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (23, 'amenity', 302, 5, 10, 'doctors');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (30, 'shop', 401, 5, 10, 'supermarket');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (31, 'amenity', 402, 5, 10, 'pharmacy');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (32, 'amenity', 403, 5, 10, 'bank');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (40, 'sport', 503, 5, 5, 'swimming');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (41, 'leisure', 501, 5, 10, 'fitness_centre');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (42, 'leisure', 502, 5, 10, 'sports_centre');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (43, 'leisure', 504, 5, 10, 'pitch');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (50, 'leisure', 601, 5, 10, 'park');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (51, 'leisure', 602, 5, 10, 'nature_reserve');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (60, 'amenity', 701, 5, 10, 'theatre');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (61, 'tourism', 702, 5, 10, 'museum');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (62, 'amenity', 703, 5, 10, 'cinema');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (63, 'amenity', 704, 5, 10, 'restaurant');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (64, 'amenity', 705, 5, 10, 'cafe');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (65, 'amenity', 705, 5, 10, 'bar');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (100, 'nivel', 201, 4, 10, 'Nivel Inicial');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (101, 'nivel', 202, 4, 10, 'Nivel Primario');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (102, 'nivel', 203, 4, 10, 'Nivel Secundario');
    INSERT INTO zonamatch.poi_mapping_rules (id, attribute, category_id, data_source_id, priority, value)
    VALUES (103, 'nivel', 205, 4, 10, 'Nivel Superior');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_data_sources_code ON zonamatch.data_sources (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_poi_categories_code ON zonamatch.poi_categories (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_poi_categories_parent_id ON zonamatch.poi_categories (parent_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_poi_mapping_rules_category_id ON zonamatch.poi_mapping_rules (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_poi_mapping_rules_data_source_id_attribute_value ON zonamatch.poi_mapping_rules (data_source_id, attribute, value);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_points_of_interest_canonical_poi_id ON zonamatch.points_of_interest (canonical_poi_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_points_of_interest_category_id ON zonamatch.points_of_interest (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_points_of_interest_data_source_id_external_id ON zonamatch.points_of_interest (data_source_id, external_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_points_of_interest_location ON zonamatch.points_of_interest USING gist (location);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_territorial_indicators_data_source_id ON zonamatch.territorial_indicators (data_source_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX "ix_territorial_indicators_territorial_unit_id_indicator_code_d~" ON zonamatch.territorial_indicators (territorial_unit_id, indicator_code, data_source_id, reference_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_territorial_units_data_source_id_external_id ON zonamatch.territorial_units (data_source_id, external_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_territorial_units_geometry ON zonamatch.territorial_units USING gist (geometry);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_territorial_units_parent_id ON zonamatch.territorial_units (parent_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_territorial_units_type_code ON zonamatch.territorial_units (type, code) WHERE code IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_territorial_units_type_normalized_name ON zonamatch.territorial_units (type, normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_zone_adjacencies_neighbor_zone_id ON zonamatch.zone_adjacencies (neighbor_zone_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_zones_slug ON zonamatch.zones (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE UNIQUE INDEX ix_zones_territorial_unit_id ON zonamatch.zones (territorial_unit_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    CREATE INDEX ix_points_of_interest_location_geography ON zonamatch.points_of_interest USING gist ((location::geography));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    PERFORM setval(
        pg_get_serial_sequence('zonamatch.data_sources', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM zonamatch.data_sources) + 1,
            nextval(pg_get_serial_sequence('zonamatch.data_sources', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('zonamatch.poi_categories', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM zonamatch.poi_categories) + 1,
            nextval(pg_get_serial_sequence('zonamatch.poi_categories', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('zonamatch.poi_mapping_rules', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM zonamatch.poi_mapping_rules) + 1,
            nextval(pg_get_serial_sequence('zonamatch.poi_mapping_rules', 'id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20261003041212_TerritorialAndPoiModel') THEN
    INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003041212_TerritorialAndPoiModel', '10.0.12');
    END IF;
END $EF$;
COMMIT;

