// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZonaMatch.Infrastructure.Data;

#nullable disable

namespace ZonaMatch.Infrastructure.Migrations
{
    [DbContext(typeof(ZonaMatchDbContext))]
    [Migration("20261010160758_AgregarRelacionUsuarioParticipante")]
    partial class AgregarRelacionUsuarioParticipante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Aporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("categoria");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaResolucion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_resolucion");

                    b.Property<string>("Horario")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("horario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("motivo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PuntoInteresId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("punto_interes_id");

                    b.Property<string>("PuntoInteresNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("punto_interes_nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("ubicacion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<bool>("ViveOTrabajaEnZona")
                        .HasColumnType("boolean")
                        .HasColumnName("vive_o_trabaja_en_zona");

                    b.Property<string>("ZonaSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("zona_slug");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PuntoInteresId", "Estado");

                    b.HasIndex("ZonaSlug", "Estado");

                    b.ToTable("aportes", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.AporteValidacion", b =>
                {
                    b.Property<Guid>("AporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("aporte_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<bool>("Confirma")
                        .HasColumnType("boolean")
                        .HasColumnName("confirma");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha");

                    b.HasKey("AporteId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("aportes_validaciones", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Comuna", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("CabaId")
                        .HasColumnType("text")
                        .HasColumnName("caba_id");

                    b.Property<string>("CensoCodigo")
                        .HasColumnType("text")
                        .HasColumnName("censo_codigo");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.HasKey("Key");

                    b.ToTable("comunas", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Escuela", b =>
                {
                    b.Property<string>("ClaveNatural")
                        .HasColumnType("text")
                        .HasColumnName("clave_natural");

                    b.Property<string>("Ambito")
                        .HasColumnType("text")
                        .HasColumnName("ambito");

                    b.Property<int?>("Anexo")
                        .HasColumnType("integer")
                        .HasColumnName("anexo");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("Calle")
                        .HasColumnType("text")
                        .HasColumnName("calle");

                    b.Property<string>("CalleLateralDerecha")
                        .HasColumnType("text")
                        .HasColumnName("calle_lateral_derecha");

                    b.Property<string>("CalleLateralIzquierda")
                        .HasColumnType("text")
                        .HasColumnName("calle_lateral_izquierda");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Cue")
                        .HasColumnType("text")
                        .HasColumnName("cue");

                    b.Property<string>("Cueanexo")
                        .HasColumnType("text")
                        .HasColumnName("cueanexo");

                    b.Property<string>("Cui")
                        .HasColumnType("text")
                        .HasColumnName("cui");

                    b.Property<string>("Dependencia")
                        .HasColumnType("text")
                        .HasColumnName("dependencia");

                    b.Property<string>("Desfavorabilidad")
                        .HasColumnType("text")
                        .HasColumnName("desfavorabilidad");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("distrito");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EscSede")
                        .HasColumnType("text")
                        .HasColumnName("esc_sede");

                    b.Property<string>("Fuente")
                        .HasColumnType("text")
                        .HasColumnName("fuente");

                    b.Property<int?>("IdDependencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_dependencia");

                    b.Property<string>("IdDistrito")
                        .HasColumnType("text")
                        .HasColumnName("id_distrito");

                    b.Property<string>("IdLocalidad")
                        .HasColumnType("text")
                        .HasColumnName("id_localidad");

                    b.Property<int?>("IdModalidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_modalidad");

                    b.Property<int?>("IdNivel")
                        .HasColumnType("integer")
                        .HasColumnName("id_nivel");

                    b.Property<int?>("IdSector")
                        .HasColumnType("integer")
                        .HasColumnName("id_sector");

                    b.Property<int?>("IdTipoOrganizacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_organizacion");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<string>("Localidad")
                        .HasColumnType("text")
                        .HasColumnName("localidad");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<int?>("Matricula")
                        .HasColumnType("integer")
                        .HasColumnName("matricula");

                    b.Property<string>("Modalidad")
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<int?>("Mujeres")
                        .HasColumnType("integer")
                        .HasColumnName("mujeres");

                    b.Property<string>("Nivel")
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroEscuela")
                        .HasColumnType("text")
                        .HasColumnName("nro_escuela");

                    b.Property<string>("PartidoKey")
                        .HasColumnType("text")
                        .HasColumnName("partido_key");

                    b.Property<string>("Periodo")
                        .HasColumnType("text")
                        .HasColumnName("periodo");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RegionEducativa")
                        .HasColumnType("text")
                        .HasColumnName("region_educativa");

                    b.Property<string>("Rpv")
                        .HasColumnType("text")
                        .HasColumnName("rpv");

                    b.Property<string>("SeccionElectoral")
                        .HasColumnType("text")
                        .HasColumnName("seccion_electoral");

                    b.Property<int?>("Secciones")
                        .HasColumnType("integer")
                        .HasColumnName("secciones");

                    b.Property<string>("Sector")
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<string>("SedeAxoExt")
                        .HasColumnType("text")
                        .HasColumnName("sede_axo_ext");

                    b.Property<string>("Subvencion")
                        .HasColumnType("text")
                        .HasColumnName("subvencion");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoOrganizacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_organizacion");

                    b.Property<string>("Turnos")
                        .HasColumnType("text")
                        .HasColumnName("turnos");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<int?>("Varones")
                        .HasColumnType("integer")
                        .HasColumnName("varones");

                    b.HasKey("ClaveNatural");

                    b.ToTable("escuelas", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InviteToken")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Groups", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupInvitations", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.MunicipioAlias", b =>
                {
                    b.Property<string>("MunicipioNombre")
                        .HasColumnType("text")
                        .HasColumnName("municipio_nombre");

                    b.Property<string>("PartidoKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partido_key");

                    b.HasKey("MunicipioNombre");

                    b.HasIndex("PartidoKey");

                    b.ToTable("municipio_alias", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Participant", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Partido", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("CensoCodigo")
                        .HasColumnType("text")
                        .HasColumnName("censo_codigo");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.HasKey("Key");

                    b.ToTable("partidos", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("texto");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ZonaSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("zona_slug");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaSlug");

                    b.ToTable("preguntas", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Radio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Comuna")
                        .HasColumnType("text")
                        .HasColumnName("comuna");

                    b.Property<string>("Depto")
                        .HasColumnType("text")
                        .HasColumnName("depto");

                    b.Property<string>("Fraccion")
                        .HasColumnType("text")
                        .HasColumnName("fraccion");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("NroRadio")
                        .HasColumnType("text")
                        .HasColumnName("radio");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.ToTable("radios", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Resena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AniosEnZona")
                        .HasColumnType("integer")
                        .HasColumnName("anios_en_zona");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("PuntajeComercios")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_comercios");

                    b.Property<int>("PuntajeConectividad")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_conectividad");

                    b.Property<int>("PuntajeEspaciosVerdes")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_espacios_verdes");

                    b.Property<int>("PuntajeSeguridad")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_seguridad");

                    b.Property<int>("PuntajeTransporte")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_transporte");

                    b.PrimitiveCollection<List<string>>("Temas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("temas");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("texto");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<bool>("Verificada")
                        .HasColumnType("boolean")
                        .HasColumnName("verificada");

                    b.Property<string>("ZonaSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("zona_slug");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaSlug", "UsuarioId")
                        .IsUnique();

                    b.ToTable("resenas", "app", t =>
                        {
                            t.HasCheckConstraint("ck_resenas_puntajes", "puntaje_seguridad BETWEEN 1 AND 5 AND puntaje_transporte BETWEEN 1 AND 5 AND puntaje_conectividad BETWEEN 1 AND 5 AND puntaje_comercios BETWEEN 1 AND 5 AND puntaje_espacios_verdes BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.ResenaVotoUtil", b =>
                {
                    b.Property<Guid>("ResenaId")
                        .HasColumnType("uuid")
                        .HasColumnName("resena_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha");

                    b.HasKey("ResenaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("resenas_votos_util", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Respuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pregunta_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("texto");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("respuestas", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Aporte", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.AporteValidacion", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Aporte", null)
                        .WithMany("Validaciones")
                        .HasForeignKey("AporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.GroupInvitation", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Group", "Group")
                        .WithMany("Invitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.MunicipioAlias", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Partido", "Partido")
                        .WithMany("Aliases")
                        .HasForeignKey("PartidoKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Participant", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Group", "Group")
                        .WithMany("Participants")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Resena", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.ResenaVotoUtil", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Resena", null)
                        .WithMany("VotosUtil")
                        .HasForeignKey("ResenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Respuesta", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Pregunta", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaMatch.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Aporte", b =>
                {
                    b.Navigation("Validaciones");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Group", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Resena", b =>
                {
                    b.Navigation("VotosUtil");
                });
#pragma warning restore 612, 618
        }
    }
}
