// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZonaMatch.Infrastructure.Data;

#nullable disable

namespace ZonaMatch.Infrastructure.Migrations
{
    [DbContext(typeof(ZonaMatchDbContext))]
    partial class ZonaMatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("zonamatch")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZonaMatch.Domain.PointsOfInterest.PoiCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<short>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<short?>("ParentId")
                        .HasColumnType("smallint")
                        .HasColumnName("parent_id");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_poi_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_poi_categories_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_poi_categories_parent_id");

                    b.ToTable("poi_categories", "zonamatch");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "transporte",
                            Name = "Transporte",
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "educacion",
                            Name = "Educación",
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "salud",
                            Name = "Salud",
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "comercios_servicios",
                            Name = "Comercios y servicios",
                            SortOrder = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "deporte",
                            Name = "Deporte",
                            SortOrder = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "espacios_verdes",
                            Name = "Espacios verdes",
                            SortOrder = (short)6
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "cultura_gastronomia",
                            Name = "Cultura y gastronomía",
                            SortOrder = (short)7
                        },
                        new
                        {
                            Id = (short)101,
                            Code = "transporte.estacion_tren",
                            Name = "Estación de tren",
                            ParentId = (short)1,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)102,
                            Code = "transporte.subte",
                            Name = "Estación de subte",
                            ParentId = (short)1,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)103,
                            Code = "transporte.parada_colectivo",
                            Name = "Parada de colectivo",
                            ParentId = (short)1,
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)104,
                            Code = "transporte.premetro",
                            Name = "Parada de premetro",
                            ParentId = (short)1,
                            SortOrder = (short)4
                        },
                        new
                        {
                            Id = (short)201,
                            Code = "educacion.jardin",
                            Name = "Jardín",
                            ParentId = (short)2,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)202,
                            Code = "educacion.primaria",
                            Name = "Escuela primaria",
                            ParentId = (short)2,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)203,
                            Code = "educacion.secundaria",
                            Name = "Escuela secundaria",
                            ParentId = (short)2,
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)204,
                            Code = "educacion.escuela",
                            Name = "Escuela (nivel sin informar)",
                            ParentId = (short)2,
                            SortOrder = (short)4
                        },
                        new
                        {
                            Id = (short)205,
                            Code = "educacion.superior",
                            Name = "Universidad o instituto superior",
                            ParentId = (short)2,
                            SortOrder = (short)5
                        },
                        new
                        {
                            Id = (short)301,
                            Code = "salud.hospital",
                            Name = "Hospital",
                            ParentId = (short)3,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)302,
                            Code = "salud.clinica",
                            Name = "Clínica o consultorio",
                            ParentId = (short)3,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)303,
                            Code = "salud.centro_salud",
                            Name = "Centro de salud (CESAC / CAPS)",
                            ParentId = (short)3,
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)401,
                            Code = "comercios_servicios.supermercado",
                            Name = "Supermercado",
                            ParentId = (short)4,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)402,
                            Code = "comercios_servicios.farmacia",
                            Name = "Farmacia",
                            ParentId = (short)4,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)403,
                            Code = "comercios_servicios.banco",
                            Name = "Banco",
                            ParentId = (short)4,
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)501,
                            Code = "deporte.gimnasio",
                            Name = "Gimnasio",
                            ParentId = (short)5,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)502,
                            Code = "deporte.club",
                            Name = "Club o polideportivo",
                            ParentId = (short)5,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)503,
                            Code = "deporte.natatorio",
                            Name = "Natatorio",
                            ParentId = (short)5,
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)504,
                            Code = "deporte.cancha",
                            Name = "Cancha",
                            ParentId = (short)5,
                            SortOrder = (short)4
                        },
                        new
                        {
                            Id = (short)601,
                            Code = "espacios_verdes.plaza_parque",
                            Name = "Plaza o parque",
                            ParentId = (short)6,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)602,
                            Code = "espacios_verdes.reserva",
                            Name = "Reserva natural",
                            ParentId = (short)6,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)701,
                            Code = "cultura_gastronomia.teatro",
                            Name = "Teatro",
                            ParentId = (short)7,
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = (short)702,
                            Code = "cultura_gastronomia.museo",
                            Name = "Museo",
                            ParentId = (short)7,
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = (short)703,
                            Code = "cultura_gastronomia.cine",
                            Name = "Cine",
                            ParentId = (short)7,
                            SortOrder = (short)3
                        },
                        new
                        {
                            Id = (short)704,
                            Code = "cultura_gastronomia.restaurante",
                            Name = "Restaurante",
                            ParentId = (short)7,
                            SortOrder = (short)4
                        },
                        new
                        {
                            Id = (short)705,
                            Code = "cultura_gastronomia.cafe_bar",
                            Name = "Café o bar",
                            ParentId = (short)7,
                            SortOrder = (short)5
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.PointsOfInterest.PoiMappingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attribute");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<short>("DataSourceId")
                        .HasColumnType("smallint")
                        .HasColumnName("data_source_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_poi_mapping_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_poi_mapping_rules_category_id");

                    b.HasIndex("DataSourceId", "Attribute", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_poi_mapping_rules_data_source_id_attribute_value");

                    b.ToTable("poi_mapping_rules", "zonamatch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attribute = "station",
                            CategoryId = (short)102,
                            DataSourceId = (short)5,
                            Priority = 5,
                            Value = "subway"
                        },
                        new
                        {
                            Id = 2,
                            Attribute = "railway",
                            CategoryId = (short)102,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "subway_entrance"
                        },
                        new
                        {
                            Id = 3,
                            Attribute = "railway",
                            CategoryId = (short)101,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "station"
                        },
                        new
                        {
                            Id = 4,
                            Attribute = "railway",
                            CategoryId = (short)101,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "halt"
                        },
                        new
                        {
                            Id = 5,
                            Attribute = "highway",
                            CategoryId = (short)103,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "bus_stop"
                        },
                        new
                        {
                            Id = 6,
                            Attribute = "railway",
                            CategoryId = (short)104,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "tram_stop"
                        },
                        new
                        {
                            Id = 10,
                            Attribute = "amenity",
                            CategoryId = (short)201,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "kindergarten"
                        },
                        new
                        {
                            Id = 11,
                            Attribute = "amenity",
                            CategoryId = (short)204,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "school"
                        },
                        new
                        {
                            Id = 12,
                            Attribute = "amenity",
                            CategoryId = (short)205,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "college"
                        },
                        new
                        {
                            Id = 13,
                            Attribute = "amenity",
                            CategoryId = (short)205,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "university"
                        },
                        new
                        {
                            Id = 20,
                            Attribute = "healthcare",
                            CategoryId = (short)303,
                            DataSourceId = (short)5,
                            Priority = 5,
                            Value = "centre"
                        },
                        new
                        {
                            Id = 21,
                            Attribute = "amenity",
                            CategoryId = (short)301,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "hospital"
                        },
                        new
                        {
                            Id = 22,
                            Attribute = "amenity",
                            CategoryId = (short)302,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "clinic"
                        },
                        new
                        {
                            Id = 23,
                            Attribute = "amenity",
                            CategoryId = (short)302,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "doctors"
                        },
                        new
                        {
                            Id = 30,
                            Attribute = "shop",
                            CategoryId = (short)401,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "supermarket"
                        },
                        new
                        {
                            Id = 31,
                            Attribute = "amenity",
                            CategoryId = (short)402,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "pharmacy"
                        },
                        new
                        {
                            Id = 32,
                            Attribute = "amenity",
                            CategoryId = (short)403,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "bank"
                        },
                        new
                        {
                            Id = 40,
                            Attribute = "sport",
                            CategoryId = (short)503,
                            DataSourceId = (short)5,
                            Priority = 5,
                            Value = "swimming"
                        },
                        new
                        {
                            Id = 41,
                            Attribute = "leisure",
                            CategoryId = (short)501,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "fitness_centre"
                        },
                        new
                        {
                            Id = 42,
                            Attribute = "leisure",
                            CategoryId = (short)502,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "sports_centre"
                        },
                        new
                        {
                            Id = 43,
                            Attribute = "leisure",
                            CategoryId = (short)504,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "pitch"
                        },
                        new
                        {
                            Id = 50,
                            Attribute = "leisure",
                            CategoryId = (short)601,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "park"
                        },
                        new
                        {
                            Id = 51,
                            Attribute = "leisure",
                            CategoryId = (short)602,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "nature_reserve"
                        },
                        new
                        {
                            Id = 60,
                            Attribute = "amenity",
                            CategoryId = (short)701,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "theatre"
                        },
                        new
                        {
                            Id = 61,
                            Attribute = "tourism",
                            CategoryId = (short)702,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "museum"
                        },
                        new
                        {
                            Id = 62,
                            Attribute = "amenity",
                            CategoryId = (short)703,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "cinema"
                        },
                        new
                        {
                            Id = 63,
                            Attribute = "amenity",
                            CategoryId = (short)704,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "restaurant"
                        },
                        new
                        {
                            Id = 64,
                            Attribute = "amenity",
                            CategoryId = (short)705,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "cafe"
                        },
                        new
                        {
                            Id = 65,
                            Attribute = "amenity",
                            CategoryId = (short)705,
                            DataSourceId = (short)5,
                            Priority = 10,
                            Value = "bar"
                        },
                        new
                        {
                            Id = 100,
                            Attribute = "nivel",
                            CategoryId = (short)201,
                            DataSourceId = (short)4,
                            Priority = 10,
                            Value = "Nivel Inicial"
                        },
                        new
                        {
                            Id = 101,
                            Attribute = "nivel",
                            CategoryId = (short)202,
                            DataSourceId = (short)4,
                            Priority = 10,
                            Value = "Nivel Primario"
                        },
                        new
                        {
                            Id = 102,
                            Attribute = "nivel",
                            CategoryId = (short)203,
                            DataSourceId = (short)4,
                            Priority = 10,
                            Value = "Nivel Secundario"
                        },
                        new
                        {
                            Id = 103,
                            Attribute = "nivel",
                            CategoryId = (short)205,
                            DataSourceId = (short)4,
                            Priority = 10,
                            Value = "Nivel Superior"
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.PointsOfInterest.PointOfInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<long?>("CanonicalPoiId")
                        .HasColumnType("bigint")
                        .HasColumnName("canonical_poi_id");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<short>("DataSourceId")
                        .HasColumnType("smallint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Footprint")
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("footprint");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<short>("Ownership")
                        .HasColumnType("smallint")
                        .HasColumnName("ownership");

                    b.Property<DateOnly?>("SourceDate")
                        .HasColumnType("date")
                        .HasColumnName("source_date");

                    b.HasKey("Id")
                        .HasName("pk_points_of_interest");

                    b.HasIndex("CanonicalPoiId")
                        .HasDatabaseName("ix_points_of_interest_canonical_poi_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_points_of_interest_category_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_points_of_interest_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_points_of_interest_data_source_id_external_id");

                    b.ToTable("points_of_interest", "zonamatch");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Sources.DataSource", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<short>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("License")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_code");

                    b.ToTable("data_sources", "zonamatch");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "zm-comunas",
                            Kind = (short)1,
                            License = "CC BY 2.5 AR",
                            Name = "Comunas de CABA",
                            Publisher = "GCBA · Buenos Aires Data",
                            Url = "https://data.buenosaires.gob.ar/dataset/comunas"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "zm-partidos",
                            Kind = (short)1,
                            License = "CC BY 4.0",
                            Name = "Partidos de la Provincia de Buenos Aires",
                            Publisher = "Datos Abiertos PBA",
                            Url = "https://catalogo.datos.gba.gob.ar/"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "zm-radios",
                            Kind = (short)1,
                            License = "CC BY 4.0",
                            Name = "Radios censales 2022",
                            Publisher = "INDEC",
                            Url = "https://www.indec.gob.ar/indec/web/Institucional-Indec-Codgeo"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "zm-escuelas",
                            Kind = (short)1,
                            License = "CC BY 4.0",
                            Name = "Padrón de establecimientos educativos",
                            Publisher = "DGCyE PBA",
                            Url = "https://abc.gob.ar/"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "osm",
                            Kind = (short)2,
                            License = "ODbL 1.0",
                            Name = "OpenStreetMap",
                            Publisher = "OpenStreetMap contributors",
                            Url = "https://www.openstreetmap.org/copyright"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "ba-barrios",
                            Kind = (short)1,
                            License = "CC BY 2.5 AR",
                            Name = "Barrios de CABA",
                            Publisher = "GCBA · Buenos Aires Data",
                            Url = "https://data.buenosaires.gob.ar/dataset/barrios"
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "community",
                            Kind = (short)2,
                            Name = "Aportes de vecinos",
                            Publisher = "Comunidad ZonaMatch"
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.TerritorialIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("DataSourceId")
                        .HasColumnType("smallint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("IndicatorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("indicator_code");

                    b.Property<DateOnly>("ReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("reference_date");

                    b.Property<long>("TerritorialUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("territorial_unit_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_territorial_indicators");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_territorial_indicators_data_source_id");

                    b.HasIndex("TerritorialUnitId", "IndicatorCode", "DataSourceId", "ReferenceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_territorial_indicators_territorial_unit_id_indicator_code_d~");

                    b.ToTable("territorial_indicators", "zonamatch");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.TerritorialUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AreaM2")
                        .HasColumnType("double precision")
                        .HasColumnName("area_m2");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<short>("DataSourceId")
                        .HasColumnType("smallint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geometry");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<DateOnly?>("SourceDate")
                        .HasColumnType("date")
                        .HasColumnName("source_date");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_territorial_units");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_territorial_units_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_territorial_units_parent_id");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_territorial_units_data_source_id_external_id");

                    b.HasIndex("Type", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_territorial_units_type_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("Type", "NormalizedName")
                        .HasDatabaseName("ix_territorial_units_type_normalized_name");

                    b.ToTable("territorial_units", "zonamatch");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("parent_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<long>("TerritorialUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("territorial_unit_id");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_zones_slug");

                    b.HasIndex("TerritorialUnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_zones_territorial_unit_id");

                    b.ToTable("zones", "zonamatch");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.ZoneAdjacency", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.Property<int>("NeighborZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("neighbor_zone_id");

                    b.HasKey("ZoneId", "NeighborZoneId")
                        .HasName("pk_zone_adjacencies");

                    b.HasIndex("NeighborZoneId")
                        .HasDatabaseName("ix_zone_adjacencies_neighbor_zone_id");

                    b.ToTable("zone_adjacencies", "zonamatch");
                });

            modelBuilder.Entity("ZonaMatch.Domain.PointsOfInterest.PoiCategory", b =>
                {
                    b.HasOne("ZonaMatch.Domain.PointsOfInterest.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_poi_categories_poi_categories_parent_id");
                });

            modelBuilder.Entity("ZonaMatch.Domain.PointsOfInterest.PoiMappingRule", b =>
                {
                    b.HasOne("ZonaMatch.Domain.PointsOfInterest.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_poi_mapping_rules_poi_categories_category_id");

                    b.HasOne("ZonaMatch.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poi_mapping_rules_data_sources_data_source_id");
                });

            modelBuilder.Entity("ZonaMatch.Domain.PointsOfInterest.PointOfInterest", b =>
                {
                    b.HasOne("ZonaMatch.Domain.PointsOfInterest.PointOfInterest", null)
                        .WithMany()
                        .HasForeignKey("CanonicalPoiId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_points_of_interest_points_of_interest_canonical_poi_id");

                    b.HasOne("ZonaMatch.Domain.PointsOfInterest.PoiCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_points_of_interest_poi_categories_category_id");

                    b.HasOne("ZonaMatch.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_points_of_interest_data_sources_data_source_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.TerritorialIndicator", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territorial_indicators_data_sources_data_source_id");

                    b.HasOne("ZonaMatch.Domain.Territory.TerritorialUnit", null)
                        .WithMany()
                        .HasForeignKey("TerritorialUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_territorial_indicators_territorial_units_territorial_unit_id");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.TerritorialUnit", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_territorial_units_data_sources_data_source_id");

                    b.HasOne("ZonaMatch.Domain.Territory.TerritorialUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_territorial_units_territorial_units_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.Zone", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Territory.TerritorialUnit", "TerritorialUnit")
                        .WithOne()
                        .HasForeignKey("ZonaMatch.Domain.Territory.Zone", "TerritorialUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zones_territorial_units_territorial_unit_id");

                    b.Navigation("TerritorialUnit");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Territory.ZoneAdjacency", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Territory.Zone", null)
                        .WithMany()
                        .HasForeignKey("NeighborZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_adjacencies_zones_neighbor_zone_id");

                    b.HasOne("ZonaMatch.Domain.Territory.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_adjacencies_zones_zone_id");
                });
#pragma warning restore 612, 618
        }
    }
}
