// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZonaMatch.Infrastructure.Data;

#nullable disable

namespace ZonaMatch.Infrastructure.Migrations
{
    [DbContext(typeof(ZonaMatchDbContext))]
    partial class ZonaMatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Comuna", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("CabaId")
                        .HasColumnType("text")
                        .HasColumnName("caba_id");

                    b.Property<string>("CensoCodigo")
                        .HasColumnType("text")
                        .HasColumnName("censo_codigo");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.HasKey("Key");

                    b.ToTable("comunas", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Escuela", b =>
                {
                    b.Property<string>("ClaveNatural")
                        .HasColumnType("text")
                        .HasColumnName("clave_natural");

                    b.Property<string>("Ambito")
                        .HasColumnType("text")
                        .HasColumnName("ambito");

                    b.Property<int?>("Anexo")
                        .HasColumnType("integer")
                        .HasColumnName("anexo");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("Calle")
                        .HasColumnType("text")
                        .HasColumnName("calle");

                    b.Property<string>("CalleLateralDerecha")
                        .HasColumnType("text")
                        .HasColumnName("calle_lateral_derecha");

                    b.Property<string>("CalleLateralIzquierda")
                        .HasColumnType("text")
                        .HasColumnName("calle_lateral_izquierda");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Cue")
                        .HasColumnType("text")
                        .HasColumnName("cue");

                    b.Property<string>("Cueanexo")
                        .HasColumnType("text")
                        .HasColumnName("cueanexo");

                    b.Property<string>("Cui")
                        .HasColumnType("text")
                        .HasColumnName("cui");

                    b.Property<string>("Dependencia")
                        .HasColumnType("text")
                        .HasColumnName("dependencia");

                    b.Property<string>("Desfavorabilidad")
                        .HasColumnType("text")
                        .HasColumnName("desfavorabilidad");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("distrito");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EscSede")
                        .HasColumnType("text")
                        .HasColumnName("esc_sede");

                    b.Property<string>("Fuente")
                        .HasColumnType("text")
                        .HasColumnName("fuente");

                    b.Property<int?>("IdDependencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_dependencia");

                    b.Property<string>("IdDistrito")
                        .HasColumnType("text")
                        .HasColumnName("id_distrito");

                    b.Property<string>("IdLocalidad")
                        .HasColumnType("text")
                        .HasColumnName("id_localidad");

                    b.Property<int?>("IdModalidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_modalidad");

                    b.Property<int?>("IdNivel")
                        .HasColumnType("integer")
                        .HasColumnName("id_nivel");

                    b.Property<int?>("IdSector")
                        .HasColumnType("integer")
                        .HasColumnName("id_sector");

                    b.Property<int?>("IdTipoOrganizacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_organizacion");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<string>("Localidad")
                        .HasColumnType("text")
                        .HasColumnName("localidad");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<int?>("Matricula")
                        .HasColumnType("integer")
                        .HasColumnName("matricula");

                    b.Property<string>("Modalidad")
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<int?>("Mujeres")
                        .HasColumnType("integer")
                        .HasColumnName("mujeres");

                    b.Property<string>("Nivel")
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroEscuela")
                        .HasColumnType("text")
                        .HasColumnName("nro_escuela");

                    b.Property<string>("PartidoKey")
                        .HasColumnType("text")
                        .HasColumnName("partido_key");

                    b.Property<string>("Periodo")
                        .HasColumnType("text")
                        .HasColumnName("periodo");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RegionEducativa")
                        .HasColumnType("text")
                        .HasColumnName("region_educativa");

                    b.Property<string>("Rpv")
                        .HasColumnType("text")
                        .HasColumnName("rpv");

                    b.Property<string>("SeccionElectoral")
                        .HasColumnType("text")
                        .HasColumnName("seccion_electoral");

                    b.Property<int?>("Secciones")
                        .HasColumnType("integer")
                        .HasColumnName("secciones");

                    b.Property<string>("Sector")
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<string>("SedeAxoExt")
                        .HasColumnType("text")
                        .HasColumnName("sede_axo_ext");

                    b.Property<string>("Subvencion")
                        .HasColumnType("text")
                        .HasColumnName("subvencion");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoOrganizacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_organizacion");

                    b.Property<string>("Turnos")
                        .HasColumnType("text")
                        .HasColumnName("turnos");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<int?>("Varones")
                        .HasColumnType("integer")
                        .HasColumnName("varones");

                    b.HasKey("ClaveNatural");

                    b.ToTable("escuelas", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.MunicipioAlias", b =>
                {
                    b.Property<string>("MunicipioNombre")
                        .HasColumnType("text")
                        .HasColumnName("municipio_nombre");

                    b.Property<string>("PartidoKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partido_key");

                    b.HasKey("MunicipioNombre");

                    b.HasIndex("PartidoKey");

                    b.ToTable("municipio_alias", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Partido", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("CensoCodigo")
                        .HasColumnType("text")
                        .HasColumnName("censo_codigo");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.HasKey("Key");

                    b.ToTable("partidos", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Radio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Comuna")
                        .HasColumnType("text")
                        .HasColumnName("comuna");

                    b.Property<string>("Depto")
                        .HasColumnType("text")
                        .HasColumnName("depto");

                    b.Property<string>("Fraccion")
                        .HasColumnType("text")
                        .HasColumnName("fraccion");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("NroRadio")
                        .HasColumnType("text")
                        .HasColumnName("radio");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.ToTable("radios", "geo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", "app");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.MunicipioAlias", b =>
                {
                    b.HasOne("ZonaMatch.Domain.Entities.Partido", "Partido")
                        .WithMany("Aliases")
                        .HasForeignKey("PartidoKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("ZonaMatch.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
